linux: use preferred_gcc instead of gcc
Homebrew/brew pull request #10569
Opened 2021-02-08 19:09 UTC by iMichka

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----

2021-02-08 19:10 UTC, iMichka commented
I need to run some sanity checks locally before shipping this. Proposed by @sjackman

2021-02-08 19:16 UTC, sjackman commented on Library/Homebrew/extend/os/linux/keg_relocate.rb
> +      gcc = Formula[preferred_gcc]
```suggestion
      gcc = Formulary.factory(preferred_gcc)
```
… for consistency with the rest of the Homebrew/brew code base.

2021-02-08 19:31 UTC, sjackman requested changes

2021-02-08 19:31 UTC, sjackman commented on Library/Homebrew/extend/ENV/shared.rb
> +    gcc = Formulary.factory(preferred_gcc)
```suggestion
    gcc = Formulary.factory("gcc")
```
This one should stay as is. It translates `gcc-10` to the formula `gcc`, which is correct on both macOS and Linux.

2021-02-08 19:31 UTC, sjackman commented on Library/Homebrew/extend/os/linux/keg_relocate.rb
> +         DevelopmentTools.non_apple_gcc_version(preferred_gcc) < gcc.version.to_i
```suggestion
         DevelopmentTools.non_apple_gcc_version("gcc") < gcc.version.to_i
```
This one needs to stay as is, it tests the version of whichever `gcc --version` is found first in the `PATH`. Line 87 immediately above however needs to change from `gcc = Formula["gcc"]` to `gcc = Formulary.factory("preferred_gcc")`

2021-02-08 19:35 UTC, sjackman commented
In `extend/os/linux/linkage_checker.rb`
```diff
-@undeclared_deps -= ["gcc", "glibc"]
+@undeclared_deps -= [preferred_compiler, "glibc"]
```

2021-02-08 19:36 UTC, sjackman commented
In `extend/os/linux/system_config.rb`
```diff
-["glibc", "gcc", "xorg"].each do |f|
+["glibc", preferred_compiler, "xorg"].each do |f|
```

2021-02-09 10:14 UTC, MikeMcQuaid approved these changes
👍🏻 once this is 💚. I really like how minimal and clean this change is ❤️

2021-02-09 17:40 UTC, sjackman commented on Library/Homebrew/compilers.rb
>      v = Formulary.factory(preferred_gcc).version.to_s.slice(/\d+/)
```suggestion
    v = Formulary.factory(CompilerSelector.preferred_gcc).version.to_s.slice(/\d+/)
```

2021-02-09 21:20 UTC, iMichka commented
I had to stub gcc@5 in the tests to make it pass. That's the only test change I had to make.

2021-02-10 02:09 UTC, sjackman approved these changes

2021-02-10 02:14 UTC, sjackman commented
I did some quick tests in the `homebrew/brew` Docker image.
✅ `brew install -sv hello` uses `/usr/bin/gcc-9` provided by the host
✅ `brew install gcc@5 && brew install -sv hello` uses `/home/linuxbrew/.linuxbrew/bin/gcc-5`

Currently `gcc` and `gcc@5` conflict, because they both provide GCC 5 until https://github.com/Homebrew/linuxbrew-core/pull/21380 is merged.

I need to think about migration issues for existing users that have `gcc` installed, because their host system is old (GCC < 5). We want it to smoothly install `gcc@5` for those users (and upgrade `gcc` to 10, but I'm less concerned about that). I don't believe `gcc@5` will be installed automatically, but I need to test that.

2021-02-10 05:53 UTC, sjackman commented
> We want it to smoothly install gcc@5 for those users (and upgrade gcc to 10, but I'm less concerned about that). I don't believe gcc@5 will be installed automatically, but I need to test that.

This sort of works! Once `gcc` is upgraded to GCC 10 and no longer provides `~/.linuxbrew/opt/gcc/bin/gcc`, when the user has no other executable named `gcc` version ≥ 5 in their `PATH`, then Homebrew will install `preferred_gcc`, aka `gcc@5`.

2021-02-10 11:01 UTC, iMichka commented
Regarding the transition phase from gcc to gcc-5 in linuxbrew-core: stuff might get broken for complex cases, especially for people which do not have gcc-5 installed. But I think we can guide them to run some commands manually to clean the mess up if anything goes wrong. But your tests tend to demonstrate that there will be no issue.

2021-02-10 11:19 UTC, MikeMcQuaid approved these changes

2021-02-10 11:20 UTC, merged

2021-02-10 17:09 UTC, sjackman commented
Thank you, Michka!