brew: disable compat mode when running sw_vers
Homebrew/brew pull request #10722
Opened 2021-02-27 05:06 UTC by gromgit

As far as I can tell, Homebrew believes Big Sur == 11.x, so we should make sure `sw_vers` doesn't output 10.16.

Addresses https://github.com/Homebrew/discussions/discussions/941

-----
- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

2021-02-27 14:27 UTC, Bo98 commented
Thinking about this again, I forgot that env filtering should have been applied here. How did this manage to slip through that?

2021-02-28 12:34 UTC, gromgit commented
>I forgot that env filtering is applied here. How did this env manage to slip through that?

That's...a very good question. :confused:

In any event, I've added another fix, to strip everything but major version from `HOMEBREW_MACOS_VERSION` for Big Sur and later, since Big Sur versions now have patchlevel numbers, so the current code incorrectly strips `11.2.1` down to `11.2`.

2021-02-28 14:15 UTC, Bo98 commented
> to strip everything but major version from `HOMEBREW_MACOS_VERSION` for Big Sur

I'm not entirely sure about this code - we don't strip _any_ patch versions for earlier macOS versions.

2021-02-28 15:56 UTC, gromgit commented
AFAICT, `HOMEBREW_OS_VERSION` (which becomes `OS_VERSION` in Ruby-land) is just a label that's added to various diagnostics outputs, so I guess it's not a critical issue. I'm just making sure the code agrees with the associated comment. :grin:

2021-03-01 13:27 UTC, MikeMcQuaid commented
> Thinking about this again, I forgot that env filtering is applied here. How did this env manage to slip through that?

Yeh, this.

I think I'd like to hold off here until we see at least one other person with this problem.

2021-03-02 10:20 UTC, MikeMcQuaid requested changes
Want to wait to see at least one other person with this problem.

2021-04-01 00:07 UTC, closed without merging