rubocops: Permit uses_from_macos "libsasl2"
Homebrew/brew pull request #10808
Opened 2021-03-08 23:15 UTC by sjackman

macOS provides `/usr/lib/libsasl2.dylib`

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

macOS Catalina 10.15 provides `/usr/lib/libsasl2.dylib`. I have not checked other versions of macOS.

2021-03-09 00:55 UTC, sjackman commented
```
1st Try error in ./test/support/helper/spec/shared_examples/formulae_exist.rb:6:
Error: RuboCop::Cop::FormulaAudit::ProvidedByMacos libsasl2 formula exists
```
https://github.com/Homebrew/brew/pull/10808/checks?check_run_id=2061171033#step:14:46

2021-03-09 11:56 UTC, MikeMcQuaid approved these changes

2021-03-09 12:52 UTC, iMichka requested changes
Debian calls this libsasl2, so let's just discuss the name first.

2021-03-09 18:40 UTC, iMichka approved these changes
I'm OK with the name.

2021-03-09 19:02 UTC, EricFromCanada commented
`/usr/lib/libsasl2.dylib` is available since at least OS X 10.10.

2021-03-10 01:15 UTC, sjackman commented
This PR is gated on `cyrus-sasl` being added to `Linuxbrew-core`. `cyrus-sasl` has been added to `Homebrew-core`.

2021-03-10 16:43 UTC, merged