docs: don't allow patches for linux formula either
Homebrew/brew pull request #11696
Opened 2021-07-12 06:12 UTC by SMillerDev

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

2021-07-12 06:14 UTC, dawidd6 approved these changes

2021-07-12 10:07 UTC, MikeMcQuaid commented
👍🏻 🙇🏻

2021-07-12 15:39 UTC, Moiss27 requested changes
i need to be closed out of this thread, i dont know anything abouy this but i know its the root of all my computers being hacked. im not asking again, delete my profile

2021-07-12 15:42 UTC, nandahkrishna commented on docs/Acceptable-Formulae.md
> +* be maintained (i.e. the last release wasn't ages ago, it works without patching on all Homebrews supported OS versions and has no outstanding, unpatched security vulnerabilities)
```suggestion
* be maintained (i.e. the last release wasn't ages ago, it works without patching on all OS versions supported by Homebrew and has no outstanding, unpatched security vulnerabilities)
```

2021-07-13 16:58 UTC, carlocab commented on docs/Acceptable-Formulae.md
> +* be maintained (i.e. the last release wasn't ages ago, it works without patching on all Homebrews supported OS versions and has no outstanding, unpatched security vulnerabilities)
Or:
```suggestion
* be maintained (i.e. the last release wasn't ages ago, it works without patching on all Homebrew-supported OS versions and has no outstanding, unpatched security vulnerabilities)
```

2021-07-13 18:49 UTC, nandahkrishna approved these changes

2021-07-13 19:18 UTC, merged