utils/pypi respect ignore_non_pypi_packages
Homebrew/brew pull request #11727
Opened 2021-07-15 20:57 UTC by brendongo

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Elsewhere on this file, the ignore_non_pypi_packages flag is used
to continue to make progress despite the existence of non-pypi resources

There is one check in the update_python_resources function that
will always `odie` if there is a non-pypi resource. This prevents
`brew bump-forumla-pr` from being run on formulas that contain
both pypi and non-pypi resources.

This PR modifies said check to not call `odie` when such resources
are encountered

2021-07-16 06:39 UTC, carlocab commented on Library/Homebrew/utils/pypi.rb
> +      if !(ignore_non_pypi_packages || print_only) && !resource.url.start_with?(PYTHONHOSTED_URL_PREFIX)
```suggestion
      if !ignore_non_pypi_packages && !print_only && !resource.url.start_with?(PYTHONHOSTED_URL_PREFIX)
```
This is a bit more readable, no?

2021-07-16 14:36 UTC, Rylan12 requested changes
This will completely delete any non-PyPI resources which is not a good idea at the moment.

When resources are automatically updated in `brew bump-formula-pr`, I think it is seen as a trusted change. Not that maintainers won't still flag things that look weird (i.e. all of a sudden all resources are deleted) but if they see that resources are automatically updated they probably won't meticulously go through to ensure it was done correctly.

Now, any `brew bump-formula-pr` on a formula with both PyPI and non-PyPI resources will break the formula by removing those non-PyPI resources without any indication. I think it's extremely likely these cases will go under the radar of maintainers.

I wouldn't be as opposed to this if it was it's own flag that wasn't run automatically on `brew bump-formula-pr`. I think we'd also need to show a warning when resources are going to be deleted.

2021-07-16 17:31 UTC, brendongo commented
@Rylan12 oh good call. Would it be acceptable behavior to keep track of the non-Pypi resources, and reprint them out to the new_resource_blocks object (in sorted order it looks like). If so I can add that change as part of this PR

2021-07-16 18:36 UTC, Rylan12 commented
Yeah, that would be great, actually!

Also, I've been wanting to rewrite that part of this to use the [`Utils::AST`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/ast.rb) module because the regex replace feels a bit tacky at the moment. I haven't really looked at the module though, so it might not be possible. Just figured I'd mention it in case it makes the work easier (but no need to switch over and add new complexity)

2021-07-19 22:49 UTC, brendongo commented
A bit swamped with other things early in the week but I should have time to get this done later in the week

2021-07-23 14:39 UTC, brendongo commented
Is there documentation on how to build/run my changes end to end?

2021-07-23 15:25 UTC, brendongo commented
Another quick question: is there a way to retrieve the raw string used to generate the Resource object in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/pypi.rb#L205 ?

2021-07-24 17:18 UTC, Rylan12 commented
> Is there documentation on how to build/run my changes end to end?

When you make changes locally, you don't need to re-build or anything like that. Just run `brew xyz` like you normally would and it should pick up your changes. If you're unsure, throw some debug messages in to make sure you're seeing their output.

Not totally sure what you mean by "end to end" here, but if it would be good to run `brew style`, `brew typecheck` and `brew tests` which will ensure you're following our style conventions, don't have any type issues, and will run our check suite.

> Another quick question: is there a way to retrieve the raw string used to generate the Resource object in https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils/pypi.rb#L205 ?

Not sure what you mean by "raw string used to generate the resource" here. The `.each` block will cycle through each resource one at a time and assign the current resource to the `resource` variable. This will be a [`Resource`](https://rubydoc.brew.sh/Resource.html) object.

There isn't really a string that defines the resource. Rather, it comes from the `resource` block in the formula definition (e.g. [here for `snakemake`](https://github.com/Homebrew/homebrew-core/blob/6a93cff22ad274ec2a49fd41fca2e754352da5ec/Formula/snakemake.rb#L22-L25)).

You can access this information using [`Resource#name`](https://rubydoc.brew.sh/Resource.html#name-instance_method) and [`Resource#url`](https://rubydoc.brew.sh/Resource.html#url-instance_method).

2021-07-27 19:51 UTC, brendongo commented
> There isn't really a string that defines the resource. Rather, it comes from the resource block in the formula definition (e.g. here for snakemake).

I mean some resources might look like 
```
   16:   resource "ivy" do
   17:     url "https://www.apache.org/dyn/closer.lua?path=ant/ivy/2.5.0/apache-ivy-2.5.0-bin.tar.gz"
   18      mirror "https://archive.apache.org/dist/ant/ivy/2.5.0/apache-ivy-2.5.0-bin.tar.gz"
   19      sha256 "3855a5769b5dbeafa9fb6a00f130467fd0f89da684a0b33a91e3dc5dae2715c7"
   20    end
```
I'm wondering if there's a way to go from resource object back to this string

2021-07-27 23:59 UTC, Rylan12 commented
Yeah, there's no on-liner to do that at the moment. It's just done manually using string interpolation for now:

https://github.com/Homebrew/brew/blob/0228c13832638e318a20411ade1159dcd19e4f38/Library/Homebrew/utils/pypi.rb#L249-L255

2021-08-25 00:03 UTC, closed without merging