install: Allow brew to install ARM packages even if terminal running in rosetta
Homebrew/brew pull request #12517
Opened 2021-12-03 19:24 UTC by nipunn1313

If terminal is running in rosetta, it's still ok to install
ARM programs, as rosetta will happily run native executables
in subprocesses. See #10313 for discussion.

This allows brew to work out-of-box on M1 macs in terminal emulators that
are currently running in rosetta (eg alacritty, kitty)

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
   - I am happy with existing test coverage on install, but would be open to adding tests with some assistance from maintainers
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

2021-12-04 01:06 UTC, nipunn1313 commented on Library/Homebrew/test/utils/analytics_spec.rb
> +        expect(described_class.os_arch_prefix_ci).to include(expected)
I realize - this is actually a pre-existing issue about running the tests on an M1
I will split it out into a separate PR

2021-12-04 01:16 UTC, nipunn1313 commented on Library/Homebrew/test/utils/analytics_spec.rb
> +        expect(described_class.os_arch_prefix_ci).to include(expected)
Split out #12518

2021-12-05 00:38 UTC, Bo98 commented
> as rosetta will happily run native executables in subprocesses.

Yes, which is why we have this message to direct people to use `arch -arm64 brew`. Otherwise subprocesses will all be run as x86_64 (including compilers if building from source).

In fact `Hardware::CPU.intel?` should return true under Rosetta so there shouldn't be any functional change from your change. So I'm not sure I understand the issue here.

2021-12-05 06:12 UTC, nipunn1313 commented
> Yes, which is why we have this message to direct people to use `arch -arm64 brew`. Otherwise subprocesses will all be run as x86_64 (including compilers if building from source).

Yep - I am trying to change the logic in brew such that this happens automatically (IE - brew realizes it's running on an ARM hardware, even though it's in a translated rosetta2 environment).

> In fact `Hardware::CPU.intel?` should return true under Rosetta so your change should still make it lead to an error. I'm not sure I understand the issue here.

YIKES. I realize my manual testing was not doing what I thought because my "HOMEBREW_PREFIX" in the dev environment was `~/src/brew` rather than `/opt/homebrew`. Good catch.

I'm doing some more careful testing to get more toward the right fix and will update the diff.

2021-12-05 06:21 UTC, nipunn1313 commented
My testing strategy here was to 

- Run on my M1 inside an emulated terminal (such that Hardware::CPU.in_rosetta2 was true). If you want to try yourselves - `brew install alacritty` should get you one.
- Patch `HOMEBREW_PREFIX.to_s == HOMEBREW_MACOS_ARM_DEFAULT_PREFIX` to `true`

run an installation of a program
```
./bin/brew reinstall entr
```

And check the file type of the installed file
```
➜  brew git:(master) file bin/entr
```

Before this diff:

```
➜  brew git:(master) ✗ ./bin/brew reinstall entr
Error: Cannot install under Rosetta 2 in ARM default prefix (/Users/nipunn/src/brew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
```

After this diff, it successfully installs (and runs)
```
➜  brew git:(master) file bin/entr
bin/entr: Mach-O 64-bit executable x86_64

➜  brew git:(master) ✗ bin/entr
release: 5.0
usage: entr [-acdnprsz] utility [argument [/_] ...] < filenames
```


I do admit that this change is happening at a super high level (`os/mac/hardware/cpu.rb`) - which is a bit scary - since it could have lots of effects I didn't anticipate. Advice appreciated. 
 And of course, if maintainers don't think it's worth pursuing such a change, that would be reasonable as well.

2021-12-06 02:54 UTC, Bo98 requested changes

2021-12-06 02:54 UTC, Bo98 commented on Library/Homebrew/extend/os/mac/hardware/cpu.rb
> +          in_rosetta2? ? :arm : :intel
This is going to break scenarios where people do want to use Intel Homebrew on an arm64 machine (e.g. `arch -x86_64 brew`).

2021-12-06 02:57 UTC, Bo98 commented
> After this diff, it successfully installs (and runs)

Wait so it installed an x86_64 executable in the arm64 prefix? That doesn't sound ideal. Mixed architectures in the same prefix will break things when it comes to libraries.

2021-12-06 14:26 UTC, carlocab commented
I don't think we need this -- we have `HOMEBREW_CHANGE_ARCH_TO_ARM` for precisely this reason:

https://github.com/Homebrew/brew/blob/dbec9de77ebc65a4845a5e672950219aa19b35b8/Library/Homebrew/brew.sh#L24-L34

Admittedly, it is undocumented and hidden in `brew.sh`, but it has the benefit of being battle-tested. Setting it should do exactly what you want `brew` to do when running under Alacritty.

The better thing to do here is to make sure this variable is documented somewhere, no?

2021-12-06 14:28 UTC, MikeMcQuaid commented
> I don't think we need this -- we have `HOMEBREW_CHANGE_ARCH_TO_ARM` for precisely this reason:

I'm not sure that's exactly the same here.

I'm not clear on what's happening with alacritty, kitty here; is `brew` being run in `x86_64` mode by default or is it being run in `arm64` mode but still technically under Rosetta (because alacritty, kitty are run under Rosetta)?

2021-12-06 14:47 UTC, carlocab commented
I'm not sure what the difference is, given that the error message that this PR appears to be trying to fix is
```
Error: Cannot install under Rosetta 2 in ARM default prefix (/Users/nipunn/src/brew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.
```
and it seems to me that the goal is to be able to elide the `arch -arm64` bit.

2021-12-06 16:08 UTC, nipunn1313 commented
`HOMEBREW_CHANGE_ARCH_TO_ARM=1` does appear to work! It's not ideal, but it does work.

I think in an ideal solution:
- It wouldn't be relevant whether or not brew itself is running as x86/arm (which appears to be derived from the terminal - or explicit `arch -arm64 brew`).
- Brew would determine default installation type based on native architecture of the system - or an explicit choice by the user, independent of the arch of the terminal environment.

There is better discussion of this in #10313

Agreed that this PR as is doesn't quite solve the issue - as it doesn't give the user a way to explicitly choose an installation type.
Was hoping to make the experience smoother, but it seems more complex than anticipated.

Closing it out. Thanks for the reviews everyone. Appreciated.

2021-12-06 16:08 UTC, closed without merging