Enables bump-formula-pr with GHES by setting HOMEBREW_GITHUB_API_URL
Homebrew/brew pull request #12898
Opened 2022-02-19 01:09 UTC by colindean

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [X] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [X] Have you successfully run `brew style` with your changes locally?
- [X] Have you successfully run `brew typecheck` with your changes locally?
- [X] Have you successfully run `brew tests` with your changes locally?

-----

Set HOMEBREW_GITHUB_API_URL to https://git.example.com/api/v3 and `bump-formula-pr` will submit to a GitHub Enterprise Server instance. This change has _only_ been live-tested with that command and no others.

A part of this is reducing the assumption that a tap is on GitHub.com and doing our best to make an effort to support GHES.

Opportunities for improvement:

* The `ALL_SCOPES_URL` in `utils/github/api.rb` and some other places where `github.com/*` is hardcoded becomes a lie when `HOMEBREW_GITHUB_API_URL` is set. Determining that dynamically would be cool.
* It'd be really cool to have bump-formula-pr and friends _just work_ without having to set the URL. This would necessitate determining if a tap is backed by GitHub/GHES on-demand or at tap time. This _could_ enable a future of supporting some other major git hosting platforms (e.g. GitLab, Gitea, BitBucket) used for private taps to give them a built-in workflow for update automation.

2022-02-19 01:10 UTC, colindean commented on Library/Homebrew/tap.rb
> +    end
I'd had this here:

```suggestion
    return unless path_base
```

but decided I liked a nice warning message better. Later on, I speculated that this method is kinda designed to fail silently for non-git taps so this warning might be too noisy…

2022-02-21 09:10 UTC, MikeMcQuaid requested changes
Thanks for the PR!

I think this code needs to be much more tightly scoped to `brew bump-formula-pr` if that's the only case you're planning on using/testing it on. `brew tap` already requires a specific URL argument for GHES so it'd make sense for `brew bump-formula-pr` to do the same.

2022-02-21 09:10 UTC, MikeMcQuaid commented on Library/Homebrew/tap.rb
> +      # consider using vendoring uri-ssh_git
No thanks 😁

2022-02-21 09:10 UTC, MikeMcQuaid commented on Library/Homebrew/tap.rb
> +      path_base = URI.parse(remote).path.delete_prefix("/")
I think it's much less clear what's going on from here. I think the original code was much easier to follow for the `github.com` case so would be good to specifically use `HOMEBREW_GITHUB_API_URL`

2022-02-21 09:10 UTC, MikeMcQuaid commented on Library/Homebrew/env_config.rb
> +      },
I think this needs to be more specific as to where it's used. It's not using this instead for e.g. all GitHub searches.

2022-02-21 09:10 UTC, MikeMcQuaid commented on Library/Homebrew/utils/github/api.rb
> +  API_URL = ENV.fetch("HOMEBREW_GITHUB_API_URL", PUBLIC_GITHUB_API_URL).freeze
This will override e.g. `brew search` behaviour which seems undesirable.

2022-03-22 00:06 UTC, closed without merging

2022-03-24 08:48 UTC, MikeMcQuaid commented on Library/Homebrew/utils/github/api.rb
> +  API_URL = ENV.fetch("HOMEBREW_GITHUB_API_URL", PUBLIC_GITHUB_API_URL).freeze
I'm game for searching internal taps but this would break searching non-internal taps.

2022-03-24 08:48 UTC, MikeMcQuaid commented on Library/Homebrew/tap.rb
> +      path_base = URI.parse(remote).path.delete_prefix("/")
Even that's not terribly easy to follow from my perspective. It feels like this needs a dedicated environment variable with the internal GHES hostname which then can be checked here and call dedicated methods for different behaviour.