Optimize `brew update` by batching `git cat-file` operations
Homebrew/brew pull request #13244
Opened 2022-05-04 14:51 UTC by boblail

| Homebrew Branch | Command | Commits Rewound | Time Elapsed | Updated Formulae |
| --- | --- | --- | --- | --- |
| `master` | `git -C "$(brew --repo homebrew/core)" reset --hard aa1b3d5df78; time sh -c "brew update &> output-2k.txt"` | 2,000 | 35.6s | 666 |
| `master` | `git -C "$(brew --repo homebrew/core)" reset --hard 11e6919661c; time sh -c "brew update &> output-20k.txt"` | 20,000 | 129.8s | 2411 |
| #13234 | `git -C "$(brew --repo homebrew/core)" reset --hard aa1b3d5df78; time sh -c "brew update &> output-2k-unfiltered.txt"` | 2,000 | 6.6s | 819 |
| #13234 | `git -C "$(brew --repo homebrew/core)" reset --hard 11e6919661c; time sh -c "brew update &> output-20k-unfiltered.txt"` | 20,000 | 10.4s | 3532 |
| _this one_ | `git -C "$(brew --repo homebrew/core)" reset --hard aa1b3d5df78; time sh -c "brew update &> output-2k-optimized.txt"` | 2,000 | 7.1s | 657† |
| _this one_ | `git -C "$(brew --repo homebrew/core)" reset --hard 11e6919661c; time sh -c "brew update &> output-20k-optimized.txt"` | 20,000 | 17.6s | 2411 |

† I haven't determined why there's a discrepancy between "Updated Formulae" on row 5 and row 1.

Fixes #13224

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

2022-05-04 15:24 UTC, boblail commented
@MikeMcQuaid, this approach makes lines like this in the specs inert:
```ruby
allow(FormulaVersions).to receive(:new).and_return(double(formula_at_revision: "2.0"))
```

If you prefer this approach to #13243, what'd be your inclination for architecture?

My first thought was to extract a class like this — that could be stubbed in a similar way:
```ruby
class FormulaeAtRevision
  def initialize(formulae, revision)
    # ...
  end

  # accepts the current version of a formula, return its version at `@revision`
  def version_of(formula)
    # ... 
  end
end
```

2022-05-05 09:09 UTC, MikeMcQuaid requested changes
Appreciate the work here but would love to avoid having a new class just for this lookback and instead look at improving `FormulaVersions` to be more performant instead.

2022-05-05 11:59 UTC, boblail commented
@MikeMcQuaid, would you be receptive to a PR that kept `git cat-file --batch` as a strategy but implemented it in `FormulaVersions` instead of `FormulaeAtRevision`?

2022-05-05 12:01 UTC, MikeMcQuaid commented
@boblail Potentially: depends on how much the complexity increases. I'm not really convinced that the solution here is in `git cat-file --batch` usage but more:

2022-05-05 12:02 UTC, MikeMcQuaid commented
- checking fewer revisions at all
- checking fewer formulae
- not checking formulae at all in some cases
- caching versions

2022-05-05 14:43 UTC, boblail commented
@MikeMcQuaid, what do you think of this refactor?

It
- discards `FormulaeAtRevision`
- extracts `GitRepositoryExtension#git_cat_files`
   (which, I think, could also optimize [formula-auditor](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/formula_auditor.rb#L719-L721) — instead of catting many formulae at one revision, we're catting one formula at many revisions, but I don't want to explode the scope of this PR 😬)
- implements `file_contents_at_revision` in terms of `repository.git_cat_file` and `formula_at_revision` in terms of `FormulaVersions.formula_from_contents` so
    1. there's not a duplication of logic between the one-off and bulk approaches for fetching previous versions of formulae
    2. the new strategy is better covered by other specs that were leveraging `FormulaVersions#formula_at_revision`

2022-05-05 14:45 UTC, boblail commented on Library/Homebrew/extend/git_repository.rb
> +        raise "that didn't work"
- [ ] Better error message

2022-05-05 15:08 UTC, boblail commented
> What's the performance benefit here for the typical and pathological cases?

@MikeMcQuaid, would you consider running `brew update` once a week typical and once every 3 months pathological?

At Square, we nudge engineers to do this monthly and we regularly see outliers who haven't done it in several months.

If so, this branch makes `brew update`
- **3.7×** faster for the typical use-case (22.6s → 6.1s)
- **9.3×** faster for the pathological use-case (135s → 14.5s)

2022-05-15 12:24 UTC, MikeMcQuaid commented
@boblail Yeh, that's a decent speedup, thanks. I'm going to want to iterate a lot on the implementation here so I'd rather if we can land something like https://github.com/Homebrew/brew/pull/13243#issuecomment-1118475144 to simplify the need for this instead.

2022-05-18 20:00 UTC, MikeMcQuaid commented
I think https://github.com/Homebrew/brew/pull/13299 may remove the need for this but interested in thoughts.

2022-06-09 09:17 UTC, MikeMcQuaid commented
Passing on this given recent `brew update` changes. Feel free to reopen if still needed/desired.

2022-06-09 09:17 UTC, closed without merging