Augment Pathname documentation
Homebrew/brew pull request #13476
Opened 2022-06-27 16:00 UTC by cpurdy

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

The changes that I am submitting are documentation only. I attempted to maintain the style of documentation that I have seen in the Ruby core libraries, as well as in the Homebrew extensions thereof. I carefully followed the guidelines from [RubyDoc](https://en.wikibooks.org/wiki/Ruby_Programming/RubyDoc), but unfortunately I do not have a local toolchain that allows me to review the final HTML result, which I would have liked to do before submitting a change. (I am willing to set up such a toolchain if required, but I don't know where to start; the various guides are all for building casks and formula.)

I included a brief description of the changes in the commit message. Is that what this question refers to: "_Have you added an explanation of what your changes do and why you'd like us to include them?_"

My purpose in expanding this documentation was to assist future formula developers from making some of the mistakes that I made, and going down some of the rabbit holes that I went down, and to (hopefully) quickly direct them to the correct solution for what they are attempting to do.

2022-06-27 20:23 UTC, EricFromCanada requested changes
This project uses Markdown rather than Rdoc, so use backticks to denote fixed-width text.

2022-06-27 20:23 UTC, EricFromCanada commented on Library/Homebrew/extend/pathname.rb
> +  # version of \Java. (+JAVA_HOME+ is not configured in the Homebrew CI environment,
remove backslash

2022-06-27 20:23 UTC, EricFromCanada commented on Library/Homebrew/extend/pathname.rb
> +  # because the +$JAVA_HOME+ from the passed environment will not be available
remove $

2022-06-27 20:23 UTC, EricFromCanada commented on Library/Homebrew/extend/pathname.rb
> +  # then use #write_env_script.
wrap method references in braces to auto-link, e.g. `{#write_env_script}`

2022-06-27 21:24 UTC, cpurdy commented
Thanks @EricFromCanada! 

I have made the necessary changes according to your instructions.

2022-06-27 21:39 UTC, cpurdy commented
Please pay no attention to the man behind the curtain. (The previous commit was a bit smaller than I intended.)

2022-06-28 15:44 UTC, cpurdy commented on Library/Homebrew/extend/pathname.rb
> +  # for shell parameter expansion; use {#write_jar_script} instead.
Let me think about it a bit, and after I digest, I'll make some edits and push back. I'll do some additions to the cookbook separately. (I try to tailor method level comments in a more focused manner, so the approach would be different in a cookbook.)

2022-07-27 00:07 UTC, closed without merging