Add `on_{system}` methods to formula cookbook
Homebrew/brew pull request #13645
Opened 2022-08-04 00:35 UTC by Rylan12

Now that we require the use of `on_{system}` blocks in homebrew/core, we should document them. This PR adds a section to the formula cookbook with information on how to use the `on_{system}` blocks and also how to use `if` statements to check the same conditions inside `def install` and `test do`

2022-08-04 10:38 UTC, MikeMcQuaid approved these changes
Great work!

2022-08-04 12:12 UTC, gromgit commented on docs/Formula-Cookbook.md
> +Inside `def install` and `test` do, don't use these `on_*` methods. Instead, use `if` statements and the following conditionals:
```suggestion
Don't use these `on_*` methods inside `def install` and `test do` blocks . Instead, use `if` statements and the following conditionals:
```

2022-08-04 12:12 UTC, gromgit commented on docs/Formula-Cookbook.md
> +  on_intel do
```suggestion
  on_arm do
```

2022-08-04 12:13 UTC, gromgit commented on docs/Formula-Cookbook.md
> +Components can also be declared for specific macOS versions or version ranges. For example, to declare a dependency only on High Sierra, nest the `depends_on` call inside an `on_high_sierra` block. A
```suggestion
Components can also be declared for specific macOS versions or version ranges. For example, to declare a dependency only on High Sierra, nest the `depends_on` call inside an `on_high_sierra` block. Add an `:or_older` or `:or_newer` parameter to the `on_high_sierra` method to add the dependency to all macOS versions that meet the condition. For example, to add `gettext` as a build dependency on Mojave and all later macOS versions, use:
```

2022-08-04 12:14 UTC, gromgit commented on docs/Formula-Cookbook.md
> +Inside `def install` and `test` do, don't use these `on_*` methods. Instead, use `if` statements and the following conditionals:
```suggestion
Inside `def install` and `test do`, don't use these `on_*` methods. Instead, use `if` statements and the following conditionals:
```

2022-08-04 12:19 UTC, gromgit requested changes
A couple of fixes and a tightening of prose.

2022-08-05 13:52 UTC, MikeMcQuaid approved these changes

2022-08-05 14:05 UTC, merged