Install the bottle dependencies
Homebrew/brew pull request #13751
Opened 2022-08-24 19:26 UTC by sjackman

The dependencies of the bottle dependencies were installed, but the actual bottle dependencies themselves were not.

- `expand_dependencies`: Install the bottle dependencies
- `bottle_dependencies`: Install `glibc` if it's too old

-----

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Bug introduced with

- <https://github.com/Homebrew/brew/pull/13494>

2022-08-24 22:15 UTC, Bo98 approved these changes
#13577 will probably supersede this as it's close to complete I think.

But focussing on this alone: changes look good to me - apologies for regression.

2022-08-25 07:45 UTC, MikeMcQuaid requested changes
Let's land https://github.com/Homebrew/brew/pull/13577 instead. It's going out in the next tag which will be 3.6.0.

2022-08-25 10:54 UTC, MikeMcQuaid commented
> Let's land #13577 instead. It's going out in the next tag which will be 3.6.0.

It's now been merged.

2022-08-26 07:31 UTC, MikeMcQuaid commented
Passing on this, seems to no longer be relevant.

2022-08-26 07:31 UTC, closed without merging

2022-08-30 16:54 UTC, sjackman commented
Superseded by PR https://github.com/Homebrew/brew/pull/13577
- https://github.com/Homebrew/brew/pull/13577