Update documentation for `brew livecheck`
Homebrew/brew pull request #13933
Opened 2022-09-27 12:51 UTC by mohammadzainabbas

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

#

This PR aims to update the documentation for `brew livecheck` (after https://github.com/Homebrew/brew/pull/13613 is merged).

@samford and @nandahkrishna, kindly have a look and let me know if we need to update some other documentation as well.

2022-09-28 03:59 UTC, samford reviewed
I ran out of time today but I will go through this tomorrow (Wednesday) when I have a chance.

However, just from a cursory glance, I see that you've converted the numbered lists from generic 1s to 1, 2, 3, etc. We intentionally use 1 for each entry because Markdown will automatically turn them into 1, 2, 3, etc. as part of rendering. With that setup, we don't have to worry about manually keeping the numbers up to date as we make changes, which also simplifies diffs. Please return these back to the previous state (i.e., uniformly using `1.`).

2022-09-28 09:45 UTC, mohammadzainabbas commented
> We intentionally use 1 for each entry because Markdown will automatically turn them into 1, 2, 3, etc. as part of rendering. With that setup, we don't have to worry about manually keeping the numbers up to date as we make changes, which also simplifies diffs. 

Oh, I didn't know this. Thanks for pointing out.

> Please return these back to the previous state (i.e., uniformly using `1.`).

Done ✅

2022-09-29 04:08 UTC, samford requested changes
From my perspective, the changes required in this documentation with respect to resource support are very minimal. The following feedback is focused on paring down the changes in this PR to only what's necessary.

2022-10-02 14:50 UTC, mohammadzainabbas commented on docs/Brew-Livecheck.md
> +The `brew livecheck` command finds the newest version of a formula, cask or resource's software by checking upstream. Livecheck has [strategies](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy.ht
Oh got it.

2022-10-02 14:53 UTC, mohammadzainabbas commented on docs/Brew-Livecheck.md
> +> Note: `--resources` flag only works with Formulae.
Okay, reverted ✅

2022-10-02 19:18 UTC, EricFromCanada requested changes

2022-10-02 19:18 UTC, EricFromCanada commented on docs/Brew-Livecheck.md
> +The `brew livecheck` command finds the newest version of a formula or cask's software software by checking upstream. Livecheck has [strategies](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy.htm
```suggestion
The `brew livecheck` command finds the newest version of a formula or cask's software by checking upstream. Livecheck has [strategies](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy.html) to identify versions from various sources, such as Git repositories, websites, etc.
```

2022-10-02 22:11 UTC, mohammadzainabbas commented on docs/Brew-Livecheck.md
> +The `brew livecheck` command finds the newest version of a formula or cask's software software by checking upstream. Livecheck has [strategies](https://rubydoc.brew.sh/Homebrew/Livecheck/Strategy.htm
Oops! Thanks for pointing it out.

2022-10-03 03:00 UTC, samford approved these changes
Thanks, @mohammadzainabbas!

2022-10-03 04:03 UTC, merged