Make Bash completions POSIX compliant
Homebrew/brew pull request #14673
Opened 2023-02-16 18:54 UTC by maxim-belkin

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

Update Bash completions to make them compatible with POSIX mode.
Related to #14643

-----

Technically, the most straightforward solution that works in POSIX and non-POSIX modes without the "while" beauty is:

```
COMPREPLY=($(compgen -W "${list}" -- "${cur}"))
```

But `brew style` complains about ☝🏻:

```
^-- SC2207 (warning): Prefer mapfile or read -a to split command output (or quote to avoid splitting).
```

Word splitting is exactly what we want, so we don't want to "quote" anything. The former of the suggested solutions (mapfile) is not available in Bash 3.2. So, below is a (the?) solution that uses `read -a` and, in my tests, works in POSIX mode. Though, to be fair, I tested in Bash 5 only.

```
IFS=$'\n' read -r -d '' -a COMPREPLY <<< "$(compgen -W "${list}" -- "${cur}")"
```

2023-02-17 13:25 UTC, MikeMcQuaid requested changes
Sorry let's hold for now and talk more about this in https://github.com/Homebrew/brew/issues/14643

2023-03-12 21:09 UTC, MikeMcQuaid commented
@maxim-belkin Is this still needed?

2023-03-14 18:37 UTC, maxim-belkin commented
> @maxim-belkin Is this still needed?

Well, I'd love to say "definitely yes", but, unfortunately, I cannot be the sole judge of the merit of the change since I am the one proposing it. I believe it is worth discussing whether Homebrew can support POSIX-compliant interactive Bash shells. Given the infrequent updates to these files, I do not anticipate it would pose any burden on maintainers.

2023-03-14 19:44 UTC, MikeMcQuaid commented
> I believe it is worth discussing whether Homebrew can support POSIX-compliant interactive Bash shells.

Ok, if this is the only scope here: given we already handled the bug I think the answer is a clear "no". Thanks anyway!

2023-03-14 19:44 UTC, closed without merging