readall: reject casks with no URL
Homebrew/brew pull request #14804
Opened 2023-02-24 18:08 UTC by Bo98

A cask without a URL is currently a valid cask. I don't understand this (except when under minimum macOS) but maybe someone can explain if there's a valid use case for that.

2023-02-24 18:21 UTC, Bo98 commented
Issues this catches:

```
Error: Invalid cask (mojave): /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/omnidisksweeper.rb
Missing URL
Error: Invalid cask (high_sierra): /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/orion.rb
Missing URL
Error: Invalid cask (sierra): /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/itsycal.rb
Missing URL
Error: Invalid cask (sierra): /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/orion.rb
Missing URL
Error: Invalid cask (el_capitan): /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/omnidisksweeper.rb
Missing URL
Error: Invalid cask (el_capitan): /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/orion.rb
Missing URL
```

* `orion`: missing `depends_on macos: ">= :mojave"` for older macOS
* `omnidisksweeper`: missing `depends_on macos: ">= :sierra"` for older macOS
* `itsycal`: missing `on_sierra` case

2023-02-24 18:34 UTC, Bo98 commented
> Issues this catches:

Which tap_syntax here apparently doesn't?

2023-02-25 01:51 UTC, Bo98 commented
> Which tap_syntax here apparently doesn't?

Ah right we seem to limit cask checks in Homebrew/brew CI to just `brew style` only.

2023-02-25 20:54 UTC, Rylan12 requested changes
Based on https://docs.brew.sh/Cask-Cookbook#required-stanzas, a `url` stanza should be required. I think the right fix here is to update the cask loader logic to fail if there's no URL

2023-02-25 21:47 UTC, Bo98 commented
Thanks, that's a useful list. It seems that casks have zero validation until install time and a lot of test fixtures (both the separate ones and embedded ones) are missing stanzas.

There's even a test for missing URL stanza which seems to be used nowhere unless code search isn't showing it? https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/support/fixtures/cask/Casks/missing-url.rb

2023-02-25 21:53 UTC, Rylan12 approved these changes
Changed my review status since this is better than nothing and shouldn't be blocked

I can open an issue to work on adding more cask validation. I know we do validation to make sure that there aren't e.g. multiple `url` stanzas, so that should probably be expanded

2023-02-25 21:59 UTC, Bo98 commented
Yeah with the way the tests are, I'm not entirely sure if there was supposed to be a original intended behaviour or what. It seems a lot of tests allow casks with missing info, but it's not entirely clear to me what you're supposed to do with said casks if you can't even install them.

I think it should be safe to reject those without a URL, version and probably sha256 at least. `desc` I seem to recall being an audit warning rather than an error.

2023-02-27 13:13 UTC, MikeMcQuaid commented
Thanks @Bo98!

2023-02-27 13:41 UTC, merged