metafiles: include `Cargo.lock` and `go.sum`
Homebrew/brew pull request #14835
Opened 2023-02-28 09:56 UTC by carlocab

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

We use `cargo` and `go` to provide external dependencies when building
some formulae. Let's install the lock files that they generate.

This will make it easier to find out the precise external dependencies
our formulae rely on, and enables auditing them for things like security
vulnerabilities.

2023-02-28 11:54 UTC, MikeMcQuaid requested changes
I don't think we should install these, they aren't useful to users. We could consider e.g. outputting their contents in `brew test-bot` runs for consumption through GitHub Actions logs instead.

2023-02-28 12:04 UTC, carlocab commented
> I don't think we should install these, they aren't useful to users. We could consider e.g. outputting their contents in `brew test-bot` runs for consumption through GitHub Actions logs instead.

Actions logs are ephemeral. If a vulnerability in a crate is disclosed (e.g. ones susceptible to [this CVE](https://github.com/rust-lang/rust/security/advisories/GHSA-r9cc-f5pr-p3j2)), then we'll need to find a way to check past logs for the problematic crate -- if the logs are even still there.

Giving users the ability to audit these lock files for themselves _is_ useful. Auditing them in CI would be even better, but I don't see how to do that properly without doing something like this.

2023-02-28 12:11 UTC, MikeMcQuaid commented
> Actions logs are ephemeral.

Are they? How long do they last until they are deleted?

> Giving users the ability to audit these lock files for themselves _is_ useful.

I don't think installing them unconditionally for all users is useful enough, given even we don't have a direct use for this yet.

> Auditing them in CI would be even better, but I don't see how to do that properly without doing something like this.

Put the files anywhere else except in the keg/bottle.

2023-02-28 12:29 UTC, carlocab commented
> > Actions logs are ephemeral.
> 
> Are they? How long do they last until they are deleted?

Yep, example: https://github.com/Homebrew/homebrew-core/pull/116495/checks

They last for at most 90 days: https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization

> > Giving users the ability to audit these lock files for themselves _is_ useful.
> 
> I don't think installing them unconditionally for all users is useful enough, given even we don't have a direct use for this yet.

I actually already have a use in mind. I'll implement it.

> > Auditing them in CI would be even better, but I don't see how to do that properly without doing something like this.
> 
> Put the files anywhere else except in the keg/bottle.

Where else can we put them? The only other natural place is the tab, but that's still in the keg/bottle. We could maybe add them to the GHP manifest, but that'll end up on disk too -- in a much less useful form.

2023-02-28 12:35 UTC, MikeMcQuaid commented
> Where else can we put them?

Somewhere else on the internet. GitHub Packages? We're going to need to start doing this for e.g. caching `brew test-bot` runs anyway.

> We could maybe add them to the GHP manifest, but that'll end up on disk too -- in a much less useful form.

Could be somewhere else on GHP that's not included in the manifest.

2023-03-23 08:41 UTC, MikeMcQuaid commented
Passing on this, sorry. Will consider the other approaches we discussed.

2023-03-23 08:41 UTC, closed without merging