SystemCommand: Annotate system_command and its derivatives.
Homebrew/brew pull request #15329
Opened 2023-04-28 17:57 UTC by Kentzo

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

2023-04-28 17:57 UTC, Kentzo commented
References https://github.com/Homebrew/brew/pull/14629

2023-04-29 07:51 UTC, reitermarkus requested changes

2023-04-29 07:51 UTC, reitermarkus commented on Library/Homebrew/cask/url.rb
> +          page = T.cast(result.stdout, T.all(String, PageWithURL))
The cast should be after the `extend` below.

2023-04-29 10:16 UTC, MikeMcQuaid commented
Thanks @Kentzo! Could you explain a little bit about how you ran into this issue?

2023-04-29 16:38 UTC, Kentzo commented
The lack of annotations for `system_command` caused one of the tests to fail in my sudo PR because sorbet saw a type cast from `Array` to `untyped`.Adding an annotation snowballed quickly into a larger diff.Best RegardsIlya KulakovOn Apr 29, 2023, at 3:16 AM, Mike McQuaid ***@***.***> wrote:﻿
Thanks @Kentzo! Could you explain a little bit about how you ran into this issue?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-04-29 19:52 UTC, dduugg commented on Library/Homebrew/cask/url.rb
>            page.extend PageWithURL
Rarely have I seen a module so clearly named to be a tuple. How much work is it to refactor as a T::Struct consisting of page and url? (I assume the string being decorated is the page?)

2023-04-29 23:42 UTC, dduugg commented on Library/Homebrew/cask/url.rb
>            page.extend PageWithURL
Something like this, as a starting point: https://github.com/Homebrew/brew/commit/8adce0f8e0dc2e192fcb8fa489f438fb4254fbf5

2023-05-06 21:46 UTC, reitermarkus commented
I have opened https://github.com/sorbet/sorbet/issues/6984, since having the shorthand

```ruby
out, err, status = system_command! "true"
```

is much more convenient to use and it mirrors `Open3.capture3`.

2023-06-05 00:06 UTC, closed without merging