brew shard: new command
Homebrew/brew pull request #15513
Opened 2023-06-04 21:09 UTC by razvanazamfirei

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [X] Have you successfully run `brew style` with your changes locally?
- [X] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

This PR adds `brew shard`, a command used to shard repositories and, more importantly, audit that files are in the correct place. 

Still needs tests written and making sure flags work as intended, but I appreciate any feedback.

Currently I'm using `git mv` for moving files in order to preserve history. It's a bit slow, but this should be noticeable only on the initial sharding.

2023-06-05 03:16 UTC, carlocab reviewed
Could you describe your intended sharding scheme/strategy here more explicitly?

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/cmd/shard.rb
Probably should be in `dev-cmd`?

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/cmd/shard.rb
> +             description: "Audit the directory for sharding."
Should this just be done by default?

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/sharder.rb
> +    success = system("git mv '#{source}' '#{destination}' 2>/dev/null")
You should probably use `system_command` here

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/sharder.rb
> +    raise "Error moving file from #{source} to #{destination}"
```suggestion
    onoe "Error moving file from #{source} to #{destination}"
    raise
```

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/sharder.rb
> +    raise "Error removing directory: #{subfolder}"
```suggestion
    onoe "Error removing directory: #{subfolder}"
    raise
```

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/sharder.rb
> +  def initialize(directory: DEFAULT_DIRECTORY, file_limit: DEFAULT_MAX_FILES, file_subset: FILE_SUBSET)
Might be nice to add type annotations to methods here.

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/sharder.rb
> +    if (subfolder.children.size - 2) > file_limit
The `- 2` is a bit cryptic here.

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/sharder.rb
> +      FileUtils.rm_rf(subfolder)
```suggestion
      subfolder.rmtree
```
Maybe?

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/sharder.rb
> +      move_file(file, directory.join(subdir, file.basename))
```suggestion
      (directory/subdir).mkpath
      move_file(file, directory/subdir/file.basename)
```

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/sharder.rb
> +      subdir = directory.join(destination_dir(file.basename.to_s, true))
```suggestion
      subdir = directory/destination_dir(file.basename.to_s, true)
```

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/sharder.rb
> +      lost_files << file if file.dirname.to_s != subdir.to_s
```suggestion
      lost_files << file if file.dirname.realpath != subdir.realpath
```

2023-06-05 03:16 UTC, carlocab commented on Library/Homebrew/sharder.rb
> +      move_file(file, directory.join(subdir, file.basename))
```suggestion
      (directory/subdir).mkpath
      move_file(file, directory/subdir/file.basename)
```

2023-06-05 11:39 UTC, razvanazamfirei commented
@carlocab, at least for `homebrew-casks` the [scheme](https://github.com/Homebrew/homebrew-cask/pull/141893) would be: 
```
#{first-letter}/#{first-letter}#{second-letter}
```
For sharding purposes, all non-alphabetical characters are replaced by `_`. This does create a case where `0-ad.rb` ends up in `_/__/0-ad.rb`. If there's a better character, happy to change it.

Not a fan of using
```
"git mv '#{source}' '#{destination}' 2>/dev/null"
```
The rationale behind it was to try and preserve the file history. `system_command` is the fallback (and much faster). 

I'll integrate the rest of the comments.

2023-06-05 13:45 UTC, MikeMcQuaid requested changes
Thanks for the PR @razvanazamfirei, it's much appreciated and I love the forward progress on sharding but I don't think it's quite the right approach for us for a few reasons:
- I don't think we need either a user-focused or developer-focused command for something that will be run only once per tap
- the auditing process should be moved into `brew audit` (or `brew style` properly but we should mostly do the right thing if they run `brew create` for something that's going to end up in the right tap
- similarly, there may be a need to teach other Homebrew internals how to generate the right shard name and this sharding logic will likely vary per-tap and is only needed on two taps (homebrew-core and homebrew-cask)

I'll reply to a couple of other things in the issue thread too.


Thanks again ❤️

2023-06-23 19:52 UTC, carlocab commented
Just leaving a note here: `brew formulae` seems to be broken by sharding. If you have `homebrew/test-bot` tapped, you see `homebrew/test-bot/t/testbottest` in the output.

2023-07-06 17:25 UTC, closed without merging