docs: Add info about tap creation
Homebrew/brew pull request #15652
Opened 2023-07-08 08:14 UTC by andy9a9

Tap directories for furmulae/casks have to be created manually. Add additional step into docu for creating them.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?

Closes #15640

2023-07-09 19:03 UTC, EricFromCanada requested changes
Nice work! Just adjusting some wording to clarify what the word "tap" means in this context.

2023-07-09 19:03 UTC, EricFromCanada commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +2. Create `tap`(Third-Party repository) directory for Homebrew formulae:
```suggestion
2. Download a local clone ("tap") the repository of core Homebrew formulae:
```

2023-07-09 19:03 UTC, EricFromCanada commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +2. Create `tap`(Third-Party repository) directory for Homebrew casks
```suggestion
2. Download a local clone ("tap") the repository of core Homebrew casks:
```

2023-07-10 11:18 UTC, andy9a9 commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +2. Create `tap`(Third-Party repository) directory for Homebrew formulae:
applied

2023-07-10 11:19 UTC, andy9a9 commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +2. Create `tap`(Third-Party repository) directory for Homebrew casks
applied

2023-07-10 17:56 UTC, EricFromCanada approved these changes

2023-07-10 17:57 UTC, merged

2023-07-10 17:58 UTC, EricFromCanada commented
It's through contributions like yours that we've been able to run this project. Thanks, @andy9a9!