extend/ENV/super: add `ENV.O2`
Homebrew/brew pull request #15680
Opened 2023-07-14 06:38 UTC by carlocab

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Having this would have been, or would be, useful on multiple occassions:

- Homebrew/homebrew-core#94724
- Homebrew/homebrew-core#136551
- #15372

I think it's time that we added this back.

2023-07-14 18:06 UTC, Slackadays commented
Why was this ever removed?

2023-07-23 16:30 UTC, apainintheneck commented
@Slackadays It looks like it was originally deprecated a few years ago in [this PR](https://github.com/Homebrew/brew/pull/10056/files#diff-14be04a3917a60d17539ef59a9727eb2e9b68501a9fb07b366b9214960b419e6) but it seems like those deprecations might be more related to monkey patching `ENV` or at least the specific reasoning wasn't mentioned there.

2023-07-23 16:31 UTC, apainintheneck approved these changes
Fine with these changes because it doesn't change the default optimization level and there are some examples of formulae that behave differently with different optimization levels. We can apply this on a case-by-case basis.

Would it make sense to add this to the docs somewhere?

2023-07-24 11:45 UTC, MikeMcQuaid requested changes
Sorry, realised I had a review here that's been `pending` for a good few days.

2023-07-24 17:33 UTC, Slackadays commented on Library/Homebrew/extend/ENV/super.rb
> +  %w[O3 O2 O1 O0 Os].each do |opt|
If we don't get O2, what will happen to the `HOMEBREW_OPTIMIZATION_LEVEL` workaround for Clipboard?

2023-07-25 02:45 UTC, apainintheneck commented on Library/Homebrew/extend/ENV/super.rb
> +    define_method opt do |&block|
Good point, I remember that being tough when I started with Ruby. Beyond that editors have better support for finding methods when they're defined directly.

2023-07-25 07:17 UTC, MikeMcQuaid commented on Library/Homebrew/extend/ENV/super.rb
> +  %w[O3 O2 O1 O0 Os].each do |opt|
Use O3, O1 or O0.

2023-07-27 05:58 UTC, carlocab commented on Library/Homebrew/extend/ENV/super.rb
> +  %w[O3 O2 O1 O0 Os].each do |opt|
Done!

2023-07-27 05:58 UTC, carlocab commented on Library/Homebrew/extend/ENV/super.rb
> +    define_method opt do |&block|
Also done.

2023-07-27 07:22 UTC, carlocab commented on Library/Homebrew/extend/ENV/super.rb
> +  %w[O3 O2 O1 O0 Os].each do |opt|
Note, however, that I added `O2` here because that's what was used/needed for Homebrew/homebrew-core#94724.

2023-07-27 11:15 UTC, MikeMcQuaid approved these changes
Looks good, thanks again @carlocab!

2023-07-27 11:15 UTC, merged