Speed up keg installation with fewer code-signing calls
Homebrew/brew pull request #15980
Opened 2023-09-08 08:19 UTC by scpeters

- [X] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [X] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [X] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [X] Have you successfully run `brew style` with your changes locally?
- [X] Have you successfully run `brew typecheck` with your changes locally?
- [X] Have you successfully run `brew tests` with your changes locally?

-----

I noticed some formulae in the `osrf/simulation` tap starting taking much longer to install on macOS Intel processors after https://github.com/Homebrew/brew/pull/15903 was merged. That only adds a call to `codesign --verify` for files, which quickly returns for unsigned files, but this code-signing method is called within loops over every library that each installed dylib links against, so it is called many times. I noticed on my machine that the `osrf/simulation/gz-sim8` formula bottle pouring time has increased from 1 minute to over 6 minutes.

I believe that the methods in `os/mac/keg` are only called from two methods in `extend/os/mac/keg_relocate`. This pull request removes the calls to `codesign_patched_binary` from `os/mac/keg` and replaces that with individual calls to that method at the end of each loop in the `relocate_dynamic_linkage` and `fix_dynamic_linkage` methods in `extend/os/Mac/keg_relocate`, which reduces bottle pouring times back to the times I was seeing before https://github.com/Homebrew/brew/pull/15903 was merged.

If we want to retain the current behavior of the methods in `os/mac/keg`, we could add to these methods an optional `codesign` parameter that defaults to true but explicitly pass `false` to those methods from `relocate_dynamic_linkage` and `fix_dynamic_linkage` (see https://github.com/Homebrew/brew/compare/master...scpeters:keg_codesign_fewer_times). Please let me know if that approach is preferred, and we can use that other branch instead, but I started with this one because it is simpler.

2023-09-08 13:38 UTC, MikeMcQuaid approved these changes
Thanks @scpeters! Makes sense to me but would love one more ✅ from one of the folks I requested before this is merged.

2023-09-08 13:54 UTC, Bo98 commented
LGTM. Though given we don't necessarily need to codesign _every_ file (e.g. if no modifications was made) and this change will start doing that, I reckon it might be worth doing a `@needs_codesigning = true` in the methods that called codesign before and then do `codesign_patched_binary(file) if @needs_codesigning`

2023-09-08 16:42 UTC, scpeters commented
> LGTM. Though given we don't necessarily need to codesign _every_ file (e.g. if no modifications was made) and this change will start doing that, I reckon it might be worth doing a `@needs_codesigning = true` in the methods that called codesign before and then do `codesign_patched_binary(file) if @needs_codesigning`. This should be even quicker in certain cases and also reduce the chance of any breakages.

Good call, you're right that this will call codesign on files that it wasn't called on before.

Small implementation question: if I'm not mistaken, `@needs_codesigning` would be an instance variable, but I think the logic depends on the `file` argument passed to the methods in `os/mac/keg`, so I think it would be more appropriate to pass `needs_codesigning` by reference to the method. Does that make sense?

2023-09-08 22:44 UTC, Bo98 commented
> Small implementation question: if I'm not mistaken, @needs_codesigning would be an instance variable, but I think the logic depends on the file argument passed to the methods in os/mac/keg, so I think it would be more appropriate to pass needs_codesigning by reference to the method. Does that make sense?

Ah yes sorry. Alternative could be to return `true/false` depending on whether the file was modified or not and do stuff like:

```rb
        needs_codesigning = false

        if file.dylib?
          id = relocated_name_for(file.dylib_id, relocation)
          needs_codesigning ||= change_dylib_id(id, file)
        end

        each_linkage_for(file, :dynamically_linked_libraries) do |old_name|
          new_name = relocated_name_for(old_name, relocation)
          needs_codesigning ||= change_install_name(old_name, new_name, file) if new_name
        end

        each_linkage_for(file, :rpaths) do |old_name|
          new_name = relocated_name_for(old_name, relocation)
          needs_codesigning ||= change_rpath(old_name, new_name, file) if new_name
        end

        codesign_patched_binary(file) if needs_codesigning
```

2023-09-09 04:50 UTC, scpeters commented
> Ah yes sorry. Alternative could be to return `true/false` depending on whether the file was modified or not and do stuff like:

Thanks, I like this so I implemented it and force-pushed to https://github.com/Homebrew/brew/commit/b3304aa91395c158fa084d57e1dfd3bbb1df816c, then realized I hadn't run `brew typecheck` and then fixed that in https://github.com/Homebrew/brew/pull/15980/commits/9235aa26c74506b28af9614f83ab0f67f34f9aba. I did have to add boolean return values in `change_rpath` in `extend/os/linux/keg_relocate` to satisfy the type checker

2023-09-09 04:57 UTC, apainintheneck reviewed
I'm pretty sure that the pattern of `needs_codesigning ||= method_call(args)` won't work the same way as before. The `||=` won't evaluate the method on the right side of the expression if `needs_codesigning` is truthy.

```rb
irb(main):015:0> val = nil
=> nil
irb(main):016:0> val ||= (puts :print; :first_value)
print
=> :first_value
irb(main):017:0> val ||= (puts :print; :second_value)
=> :first_value
```

Off the top of my head, you could do.

```rb
needs_codesigning = method_call(args) || needs_codesigning
```

```rb
needs_codesigning = []
needs_codesigning << method_call(args)
...
if needs_codesigning.any?
...
```

2023-09-09 05:18 UTC, apainintheneck requested changes
Looking at this a bit more my previous comment needs to be addressed before this is ready to merge.

2023-09-09 13:50 UTC, Bo98 commented
Sorry, yeah I oversimplified it. Idea in my head was

```rb
modified = change_dylib_id(...)
need_codesigning ||= modified
```

Array also works too though.

2023-09-09 16:23 UTC, apainintheneck commented
I doubt the loops go on that long but probably better to avoid arrays just in case. @Bo98's solution above should work well.

2023-09-09 19:55 UTC, scpeters commented
> ```ruby
> modified = change_dylib_id(...)
> need_codesigning ||= modified
> ```

applied in https://github.com/Homebrew/brew/pull/15980/commits/27901bcc77be43cbf56282102b56d4ad9af96f35

and wow, satisfying typecheck with boolean types was very confusing

2023-09-09 20:02 UTC, apainintheneck approved these changes

2023-09-10 01:15 UTC, scpeters commented
I just squashed and rebased on master

2023-09-11 12:01 UTC, MikeMcQuaid approved these changes
Looks good to me, thanks again @scpeters!

2023-09-11 12:01 UTC, merged