dev-cmd/edit: do not shadow formula with local dir
Homebrew/brew pull request #16030
Opened 2023-09-25 14:52 UTC by abitrolly

Fix for `brew edit <name>` to ignore local dir with the same name as formula and edit formula instead.

Fixes #16015.

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

2023-09-25 14:53 UTC, Bo98 commented
Does `brew style` support directories? If so, this would break that.

2023-09-25 14:58 UTC, abitrolly commented
@Bo98 I don't know. `brew style` didn't fail, and I don't think I am capable to write a test case for it.

2023-09-25 15:40 UTC, MikeMcQuaid commented
Sorry, I don't think we want this. People will complain. Instead, we should output the fully qualified local path in this case to make clear what's been edited.

2023-09-25 16:06 UTC, abitrolly commented
Why people want to open local dir with `brew edit dir` instead of doing `vim dir`?

Maybe I don't know something, but isn't `brew edit` for editing formulas and not local dirs?

2023-09-26 02:57 UTC, apainintheneck requested changes
Thanks for taking a stab at this but this is not the right approach.

`brew style` can be called on any directory or file and this is useful sometimes when working on local taps or package changes.

It'd probably be best to keep discussion to the original issue (https://github.com/Homebrew/brew/issues/16015) before we decide more generally on how we want to fix this problem.

2023-09-26 11:03 UTC, MikeMcQuaid commented
> `brew style` can be called on any directory or file and this is useful sometimes when working on local taps or package changes.

Yes, I use `brew style .` all the time, including on non-taps.

2023-09-27 01:25 UTC, closed without merging