sudo: Prioritize sudo_as_root over HOMEBREW_SUDO_THROUGH_SUDO_USER.
Homebrew/brew pull request #16368
Opened 2023-12-20 06:41 UTC by Kentzo

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

`sudo_as_root` is reserved for cases where a command must be run as root and root only. No other user can suffice regardless of group and/or ACLs. Therefore it should be preferred over `HOMEBREW_SUDO_THROUGH_SUDO_USER`.

2023-12-20 12:05 UTC, MikeMcQuaid requested changes
Thanks for the PR!

This is not correct, sorry, I think you may have misunderstood what `Homebrew::EnvConfig.sudo_through_sudo_user?` does. 

`Homebrew::EnvConfig.sudo_through_sudo_user?` means that if I'm a user that cannot `sudo` to `root` then it instead `sudo`s to an intermediate user who then `sudo`s to `root`. This change would break that flow.

It may be that setting `Homebrew::EnvConfig.sudo_through_sudo_user?` breaks what you intended with `sudo_as_root?` and that the `-u root` should be part of another `if` rather than an `elsif` but it's definitely not correct as-is, sorry.

2023-12-20 17:31 UTC, Kentzo commented
Ah, indeed. I linked value of `homebrew_sudo_user` to `HOMEBREW_SUDO_THROUGH_SUDO_USER`.

> if I'm a user that cannot sudo to root then it instead sudos to an intermediate user who then sudos to root

Could you walk me through a specific use-case, step-by-step? Because in the current implementation I don't see how this is possible 

The way I understand it is:
```
$ whoami
userA
$ sudo -u userB HOMEBREW_SUDO_THROUGH_SUDO_USER=1 brew install …
# ...
# when brew runs a system command with `sudo: true`, it does it via `sudo -u userA`
# because external sudo will set SUDO_USER=userA
# ...
```

2023-12-20 17:33 UTC, MikeMcQuaid commented
> Could you walk me through a specific use-case, step-by-step? Because in the current implementation I don't see how this is possible

I can't really walk you through it all. It's possible because I use it daily 😉

2023-12-20 17:44 UTC, Kentzo commented
Allow me to nitpick the prompt: `sudo` can be configured such that the user whose password is being requested is not the same user that is used to run command. Please consider using something like `"Password of '%p' to run as '%U': "`.

2023-12-20 19:20 UTC, Kentzo commented
Updated the PR to add `-u root` even when `HOMEBREW_SUDO_THROUGH_SUDO_USER` is specified, because the `sudo_as_root: true` commands still want `root` regardless of who is running sudo.

2023-12-21 08:39 UTC, MikeMcQuaid commented on Library/Homebrew/system_command.rb
> +    user_flags += sudo_as_root? ? ["-u", "root"] : []
```suggestion
    user_flags += ["-u", "root"] if sudo_as_root?
```

2023-12-21 09:21 UTC, MikeMcQuaid approved these changes

2023-12-21 10:08 UTC, merged

2023-12-21 10:08 UTC, MikeMcQuaid commented
Looks good in local testing, thanks again @Kentzo!