Simplify `Tap#remote_repo`.
Homebrew/brew pull request #16776
Opened 2024-02-29 21:48 UTC by reitermarkus

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

Extracted from https://github.com/Homebrew/brew/pull/16730 for easier review.

2024-03-01 03:26 UTC, apainintheneck commented
I'm not sure this is really simpler. It's a few less lines I guess.

2024-03-01 08:39 UTC, MikeMcQuaid commented
Agreed with @apainintheneck, this is worse as it actually introduces more branching logic despite being fewer lines. Passing on this, sorry.

2024-03-01 11:01 UTC, reitermarkus commented
It's needed for Sorbet to work. Note the signature is added in a later commit in the original PR.

2024-03-01 11:03 UTC, reitermarkus commented
Feel free to suggest an alternative that only calls `remote` once.

2024-03-01 13:42 UTC, MikeMcQuaid commented
> Feel free to suggest an alternative that only calls `remote` once.

`remote_repo = remote` and then use that variable instead.

2024-03-02 02:20 UTC, apainintheneck commented
> It's needed to work with the signature of `Tap#remote`, which is added in a later commit in the original PR.

In that case, I'm okay with whatever appeases the type system. That goes for other PR too.

2024-03-02 23:40 UTC, apainintheneck commented
@reitermarkus Maybe this shouldn't be a separate PR in that case though. It'd be easier to understand in context. That being said I appreciate you breaking up these in general PRs so they're easier to review.

2024-03-04 09:28 UTC, MikeMcQuaid requested changes

2024-03-04 09:28 UTC, MikeMcQuaid commented on Library/Homebrew/tap.rb
> +                           &.delete_suffix(".git")
```suggestion
    return unless (remote_repo = remote)

    @remote_repo ||= remote_repo.delete_prefix("https://github.com/")
                                .delete_prefix("git@github.com:")
                                .delete_suffix(".git")
```

2024-03-04 14:00 UTC, MikeMcQuaid approved these changes

2024-03-04 14:00 UTC, merged

2024-03-04 14:00 UTC, MikeMcQuaid commented
Thanks @reitermarkus!