sandbox: only allow local network operations
Homebrew/brew pull request #17703
Opened 2024-07-13 19:11 UTC by nandahkrishna

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew typecheck` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

This PR is an attempt to restrict network operations in the sandbox (for `build`, `postinstall` and `test`) to just local network operations. The sandbox rules were inspired from: https://github.com/bazelbuild/bazel/blob/4d62c8f7557a4673ffe5600f963fdfddd7b99d3b/src/main/java/com/google/devtools/build/lib/sandbox/DarwinSandboxedSpawnRunner.java#L300-L302

This might have to be modified a bit and may cause problems with a bunch of formulae too, so further testing will be required. CC @woodruffw.

2024-07-13 19:23 UTC, Bo98 commented
This will definitely break a lot, including all formulae that uses a language package manager (npm, cargo, etc.) as we don't use resources for those with sufficient lockfiles.

2024-07-13 19:29 UTC, nandahkrishna commented
Based on a short discussion with Mike, we thought it might be good have a separate `fetch` block/phase which does have network access but restricted write permissions. This would just download all these dependencies to the cache and then the `install` phase would be able to use these. I'm going to spend some time to try and implement that if it makes sense.

2024-07-14 18:35 UTC, woodruffw approved these changes

2024-07-14 18:36 UTC, woodruffw requested changes
Sorry, premature review -- sounds like there's still some stuff to be done here 🙂

2024-08-12 14:45 UTC, closed without merging