attestion: make `InvalidAttestationError` non-fatal in CI
Homebrew/brew pull request #18485
Opened 2024-10-03 09:04 UTC by carlocab

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

I don't think I've seen an `InvalidAttestationError` that wasn't some
sort of network problem (e.g., rate limit, connection timeout, 503).
Let's emit a warning instead of erroring out.

Note that `MissingAttestationError` is still fatal, and that will still
produce errors in CI.

2024-10-03 09:42 UTC, MikeMcQuaid requested changes
I appreciate the intent here but 👎🏻 as-is.

If we're going to make this non-fatal it feels like it defeats the entire point of having attestation. 

I'd like to have us try a couple of retries with an exponential backoff before we do this.

2024-10-03 18:45 UTC, dduugg commented
> ```
> attestation.rb:135: Method `system_command!` does not exist on `T.class_of(Homebrew::Attestation)` https://srb.help/7003
>      135 |        result = system_command!(gh_executable, args: cmd,
>                            ^^^^^^^^^^^^^^^
> Errors: 1
> ```
> 
> Huh, interesting. Not even code I touched though. Would love a suggestion here. CC @dduugg ?

Try pairing this with an explicit `begin`, i don't think the way code aligns matches the control flow. (Then, I think you should be getting a different type error, since you've made the return type nilable)

2024-10-04 04:45 UTC, carlocab commented
Implemented retry logic instead.

2024-10-04 07:32 UTC, MikeMcQuaid approved these changes
Thanks @carlocab! Have suggested speeding up failure time so we can evaluate if this is something we should back out entirely for now. Feel free to merge as-is if preferred.

2024-10-04 07:32 UTC, MikeMcQuaid commented on Library/Homebrew/attestation.rb
> +      sleep_time = 3 ** @attestation_retry_count[bottle]
```suggestion
      sleep_time = 2 ** @attestation_retry_count[bottle]
```
would be fine with me if you want this to take smaller jumps/be quicker to fail

2024-10-04 07:32 UTC, MikeMcQuaid commented on Library/Homebrew/attestation.rb
> +    ATTESTATION_MAX_RETRIES = 5
```suggestion
    ATTESTATION_MAX_RETRIES = 2
```
or 
```suggestion
    ATTESTATION_MAX_RETRIES = 3
```
would be fine with me if you want to fail earlier

2024-10-04 08:02 UTC, carlocab commented
Let's keep the retry timing as is. The case for backing this out if we need to will be stronger if we were more patient about retries.

2024-10-04 08:09 UTC, merged