Set CMAKE_BUILD_PARALLEL_LEVEL environment variable.
Homebrew/brew pull request #18558
Opened 2024-10-13 02:35 UTC by dhull

`cmake` builds previously did not respect `HOMEBREW_MAKE_JOBS`.  This change fixes that.

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew typecheck` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?

-----

2024-10-16 00:11 UTC, Bo98 approved these changes
Change looks OK.

Though not entirely sure what scenario this would have applied given `cmake` already respects `MAKEFLAGS` which we set? Do you have a reproducer?

2024-10-16 02:05 UTC, cho-m commented
Need to update `deparallelize` too.

As far as I can tell:
* Unix Makefiles should use MAKEFLAGS already so shouldn't be impacted
* Ninja defaults to all CPUs. We have a `ninja` shim but `cmake --build` does not use it. So setting `CMAKE_BUILD_PARALLEL_LEVEL` will help, but mainly for reducing the parallelization (i.e. setting a lower `HOMEBREW_MAKE_JOBS`)
* Should allow controlling parallelization for other generators like Xcode. We don't use them in Homebrew/core but maybe 3rd party taps do.

2024-10-16 07:21 UTC, MikeMcQuaid requested changes
Need to update `ENV.deparallelize` too (as mentioned by @cho-m).

Marking as request changes just to ensure it's not merged by mistake before that.

2024-10-18 01:09 UTC, dhull commented
> Though not entirely sure what scenario this would have applied given `cmake` already respects `MAKEFLAGS` which we set? Do you have a reproducer?

Yes.

I have a old Mac running MacOS Big Sur 11.7.10 (the latest version of the OS supported on this Mac) so homebrew needs to compile packages when I install them. My Mac has 8 cores and 16 GB RAM and some of the builds occasionally fails because they run out of memory, with 8 cmake jobs running. I tried setting `CMAKE_BUILD_PARALLEL_LEVEL` in my environment but discovered that `brew` cleared it and so it had no effect. I then tried setting `HOMEBREW_MAKE_JOBS` and found 8 cmake jobs still ran. Finally I made this change and then the number of cmake jobs was limited by `HOMEBREW_MAKE_JOBS`.

2024-10-18 02:07 UTC, carlocab commented
> We have a `ninja` shim but `cmake --build` does not use it. 

Kinda weird that it doesn't, since `cmake --build` will happily take any `ninja` in `PATH` outside of `brew`.

2024-10-18 02:40 UTC, cho-m commented
> Kinda weird that it doesn't, since `cmake --build` will happily take any `ninja` in `PATH` outside of `brew`.

CMake uses `find_program` so some other locations take precedence over `PATH` like:
https://github.com/Homebrew/brew/blob/215064e9cdcb9c1e52cbf1f61d3fcccc988c4af6/Library/Homebrew/extend/ENV/super.rb#L257-L260

2024-11-16 00:15 UTC, closed without merging