workflows: migrate to GitHub Container Registry.
Homebrew/brew pull request #8569
Opened 2020-09-02 11:37 UTC by MikeMcQuaid

This seems a better fit for us (unauthenticated anonymous access) than GitHub Packages Docker registry was.

Followed steps on https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [x] Have you successfully run `brew style` with your changes locally?
- [x] Have you successfully run `brew tests` with your changes locally?

-----

2020-09-02 12:00 UTC, MikeMcQuaid commented
@sjackman @jonchang This won't actually push any changes as-is until tagged or on the `master` branch. Will merge when you're 👍🏻 and fix/revert depending on the `master` builds. Might be nice to get this in for 2.5.0 so we can announce it there.

2020-09-03 00:04 UTC, sjackman requested changes
https://docs.github.com/en/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images#domain-changes

> `docker.pkg.github.com/OWNER/REPOSITORY/IMAGE_NAME`
> `ghcr.io/OWNER/IMAGE_NAME`

Notice that it's not `ghcr.io/OWNER/REPOSITORY/IMAGE_NAME` but instead `ghcr.io/OWNER/IMAGE_NAME`, so `ghcr.io/homebrew/brew/…` needs to change to `ghcr.io/homebrew/…` throughout.

2020-09-03 00:28 UTC, maxim-belkin commented
It also needs a new PAT as it can't use GITHUB_TOKEN:

> GitHub Container Registry does not support using GITHUB_TOKEN for your PAT so you must use a different custom variable, such as CR_PAT. For more information, see "Creating and storing encrypted secrets."

2020-09-03 08:33 UTC, MikeMcQuaid commented
> Notice that it's not `ghcr.io/OWNER/REPOSITORY/IMAGE_NAME` but instead `ghcr.io/OWNER/IMAGE_NAME`, so `ghcr.io/homebrew/brew/…` needs to change to `ghcr.io/homebrew/…` throughout.

Done!

2020-09-03 08:41 UTC, MikeMcQuaid commented
> It also needs a new PAT as it can't use GITHUB_TOKEN

Done!

2020-09-03 09:04 UTC, merged

2020-09-03 09:04 UTC, MikeMcQuaid commented
Let's see how this goes 🤞🏻

2020-09-03 13:31 UTC, MikeMcQuaid commented
Working (finally): https://github.com/Homebrew/brew/runs/1066866856#step:24:1