Markdown changes
Homebrew/brew pull request #8809
Opened 2020-09-26 16:25 UTC by domitechnshimba

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/brew/blob/HEAD/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/brew/pulls) for the same change?
- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your changes? [Here's an example](https://github.com/Homebrew/brew/blob/HEAD/Library/Homebrew/test/PATH_spec.rb).
- [ ] Have you successfully run `brew style` with your changes locally?
- [ ] Have you successfully run `brew tests` with your changes locally?
- [ ] Have you successfully run `brew man` locally and committed any changes?

-----

2020-09-26 17:13 UTC, reitermarkus requested changes

2020-09-26 17:13 UTC, reitermarkus commented on docs/Gems,-Eggs-and-Perl-Modules.md
> +### So why was I using sudo
Re-add the question mark.

2020-09-26 19:00 UTC, reitermarkus commented
@domitechnshimba, please squash this into one commit with a more descriptive commit message.

2020-09-26 19:51 UTC, reitermarkus requested changes

2020-09-26 19:51 UTC, reitermarkus commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +* `<YOUR_USERNAME>` is your GitHub username, not your local machine username.
This should stay in `3.`.

2020-09-26 19:51 UTC, reitermarkus commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +* `<YOUR_USERNAME>` is your GitHub username, not your local machine username.
This should stay in `3.`.

2020-09-26 19:51 UTC, reitermarkus commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +* This creates a personal remote repository that you can push to. This is needed because only Homebrew maintainers have push access to the main repositories.
This should stay in `1.`.

2020-09-26 19:51 UTC, reitermarkus commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +* If there's a `bottle do` block in the formula, don't remove or change it; we'll update it when we pull your PR.
This should stay in `4.`.

2020-09-26 19:51 UTC, reitermarkus commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +* Please note that our preferred commit message format for simple version updates is "`<FORMULA_NAME> <NEW_VERSION>`", e.g. "`source-highlight 3.1.8`".
This should stay in `6.`.

2020-09-26 19:51 UTC, reitermarkus commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +* A `needs response` label on a PR means that the Homebrew maintainers need you to respond to previous comments.
This should stay in `2.`.

2020-09-26 19:51 UTC, reitermarkus commented on docs/How-To-Open-a-Homebrew-Pull-Request.md
> +* If you are working on a PR for a single formula, `git commit --amend` is a convenient way of keeping your commits squashed as you go.
This should stay in `3.`.

2020-09-26 19:51 UTC, reitermarkus commented on docs/Releases.md
> +- Cons: negative comments are common and people take this as a chance to complain about Homebrew (regardless of their usage)
These should stay in `5.`.

2020-09-26 20:20 UTC, domitechnshimba commented on docs/Gems,-Eggs-and-Perl-Modules.md
> +### So why was I using sudo
I have added a question mark

2020-09-29 07:38 UTC, MikeMcQuaid commented
Passing on this, sorry!

2020-09-29 07:38 UTC, closed without merging