macOS Big Sur
Homebrew/brew pull request #9054
Opened 2020-11-05 22:40 UTC by fxcoudert

Not yet ready for merging, to be shipped as soon as Big Sur shipped

2020-11-06 00:03 UTC, jonchang commented on Library/Homebrew/os/mac/xcode.rb
>          when "10.15" then latest_stable
```suggestion
        when "11.0"  then latest_stable
        when "10.15" then "12.2"
```

2020-11-06 09:12 UTC, MikeMcQuaid commented
> * to be shipped as soon as Big Sur ships.

I don't think this can ship until at least https://github.com/Homebrew/brew/pull/9010 does and/or we have working homebrew-core CI.

2020-11-12 16:22 UTC, MikeMcQuaid requested changes
This should not ship until we have working Big Sur CI. We cannot support what we do not have CI for.

2020-11-13 06:40 UTC, dvaldivia commented
Will this PR make it so homebrew only works with XCode 12.2 for macOS Big Sur 11.0?

2020-11-13 08:49 UTC, fxcoudert commented
We only support the latest Xcode on all platforms

2020-11-13 17:00 UTC, dvaldivia commented
@fxcoudert my bad, I though XCode 12.1 was the lastest for macOS 11.0

2020-11-14 08:19 UTC, mathieuhendey commented
Now that Xcode 12.2 has been released through the App Store (along with its CLI tools (see image), can this be merged?

![Screenshot 2020-11-14 at 08 19 32](https://user-images.githubusercontent.com/1131786/99143011-22ec0900-2652-11eb-9c61-c0129f678436.png)

2020-11-14 19:48 UTC, dvaldivia commented
@mathieuhendey seems they are waiting to set up some CI for Big Sur

2020-11-14 19:50 UTC, fxcoudert commented
@mathieuhendey we are setting up a CI and will start supporting Big Sur as soon as we are ready

2020-11-14 23:00 UTC, fxcoudert commented
Rebasing. I'm upping the minimum Xcode for Big Sur to 12.2 because 12.0 did not have a Big Sur SDK. 12.2 is the version that coincided with the Big Sur release, as well.

2020-11-14 23:05 UTC, fxcoudert commented
I think it is time for this PR, and companion https://github.com/Homebrew/install/pull/346
- We have nodes available for Homebrew core, we have 15% coverage of core bottles in 12 hours.
- There have been no major crisis
- We're likely to turn on Big Sur CI for all formulas in 24 to 48 hours (i.e., around Monday)
- For things that are not bottled, Catalina bottles are used anyway

2020-11-15 09:43 UTC, fxcoudert commented
and Big Sur CI is now turned on

2020-11-16 12:22 UTC, MikeMcQuaid approved these changes

2020-11-16 12:22 UTC, MikeMcQuaid commented
Thanks @fxcoudert!

2020-11-16 12:22 UTC, merged